# Generated by Django 5.2 on 2025-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('partner', 'Partner'), ('support_agent', 'Support Agent')], default='partner', max_length=15),
        ),
    ]
