# Generated by Django 5.2 on 2025-05-02 13:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        ('referrals_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('crypto', 'Cryptocurrency')], max_length=10)),
                ('payment_details', models.JSONField(default=dict)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, help_text='Internal notes for this payout', null=True)),
                ('client_notes', models.TextField(blank=True, help_text='Notes visible to the partner', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(help_text='The partner receiving this payout', on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='partner.partnerprofile')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who requested this payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('bonus', 'Bonus'), ('promotion', 'Promotion'), ('other', 'Other')], default='referral', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('available', 'Available'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_earnings', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='partner.partnerprofile')),
                ('referral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning', to='referrals_management.referral')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_included', to='payouts.payout')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='payouts.payout')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_referrals', to='referrals_management.referral')),
            ],
            options={
                'verbose_name': 'Payout Referral',
                'verbose_name_plural': 'Payout Referrals',
            },
        ),
        migrations.CreateModel(
            name='PayoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('mpesa', 'M-Pesa'), ('crypto', 'Cryptocurrency')], default='bank', max_length=10)),
                ('payment_details', models.JSONField(default=dict)),
                ('minimum_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('auto_payout', models.BooleanField(default=False)),
                ('payout_schedule', models.CharField(choices=[('manual', 'Manual'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_setting', to='partner.partnerprofile')),
            ],
            options={
                'verbose_name': 'Payout Setting',
                'verbose_name_plural': 'Payout Settings',
            },
        ),
        migrations.CreateModel(
            name='PayoutTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_status_changes', to=settings.AUTH_USER_MODEL)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='payouts.payout')),
            ],
            options={
                'verbose_name': 'Payout Timeline',
                'verbose_name_plural': 'Payout Timelines',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'request_date'], name='payouts_pay_status_d13ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['partner', 'status'], name='payouts_pay_partner_cbd910_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payoutreferral',
            unique_together={('payout', 'referral')},
        ),
    ]
