# Generated by Django 5.2 on 2025-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
