# Generated by Django 5.2 on 2025-05-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_earnings_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
