# Generated by Django 5.2 on 2025-04-30 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('payouts', '0003_remove_earnings_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='client_notes',
            field=models.TextField(blank=True, help_text='Notes visible to the partner', null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who requested this payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payout',
            name='note',
            field=models.TextField(blank=True, help_text='Internal notes for this payout', null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='partner',
            field=models.ForeignKey(help_text='The partner receiving this payout', on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='partner.partnerprofile'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who processed this payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PayoutTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_status_changes', to=settings.AUTH_USER_MODEL)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='payouts.payout')),
            ],
            options={
                'verbose_name': 'Payout Timeline',
                'verbose_name_plural': 'Payout Timelines',
                'ordering': ['-timestamp'],
            },
        ),
    ]
