# Generated by Django 5.2 on 2025-05-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_earnings_rejection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='paid_date',
            field=models.DateTimeField(blank=True, help_text='When these earnings were paid out', null=True),
        ),
    ]
