# Generated by Django 5.2 on 2025-05-01 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('payouts', '0006_earnings_created_by_payout_client_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnings',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='client_notes',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='requested_by',
        ),
        migrations.AlterField(
            model_name='payout',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='partner.partnerprofile'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PayoutTimeline',
        ),
    ]
