# Generated by Django 5.2 on 2025-05-06 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Requirement name', max_length=255)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('other', 'Other')], default='pdf', help_text='Type of document required', max_length=10)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this document is mandatory')),
                ('description', models.TextField(blank=True, help_text='Additional details about the requirement', null=True)),
                ('max_file_size', models.PositiveIntegerField(default=5242880, help_text='Maximum file size in bytes')),
                ('allowed_extensions', models.CharField(default='.pdf,.jpg,.jpeg,.png', help_text='Comma-separated list of allowed file extensions', max_length=255)),
                ('expiration_period_days', models.PositiveIntegerField(blank=True, help_text='Number of days until document is considered expired (null if no expiration)', null=True)),
                ('active', models.BooleanField(default=True, help_text='Whether this requirement is currently active')),
            ],
            options={
                'verbose_name': 'Document Requirement',
                'verbose_name_plural': 'Document Requirements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional details about this document', null=True)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('other', 'Other')], default='pdf', help_text='Type of document', max_length=10)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('missing', 'Missing'), ('required', 'Required')], default='required', help_text='Current status of the document', max_length=10)),
                ('file', models.FileField(blank=True, help_text='Uploaded document file', null=True, upload_to='documents/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, help_text='File MIME type', max_length=100, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this document was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this document was last updated')),
                ('verification_date', models.DateTimeField(blank=True, help_text='When this document was verified', null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from the verification process', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Staff member who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
                'permissions': [('verify_document', 'Can verify document status'), ('view_all_documents', 'Can view all user documents')],
            },
        ),
    ]
