# Generated by Django 5.2 on 2025-04-26 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='testimonials/videos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOnboardingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_onboarding_links', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_onboarding_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('support_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('svg_image', models.TextField(blank=True, null=True)),
                ('process_link', models.URLField(blank=True, max_length=255, null=True)),
                ('exclusive', models.BooleanField(default=False)),
                ('booking_path', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.JSONField(default=dict)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='partner_pro_is_acti_d5fa2d_idx'), models.Index(fields=['category'], name='partner_pro_categor_f90cf3_idx'), models.Index(fields=['type'], name='partner_pro_type_2f7041_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('referral_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('referral_link', models.CharField(editable=False, max_length=255, unique=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('generated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('support_availability', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('blue', 'Blue'), ('green', 'Green')], default='light', max_length=10)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
                ('selected_products', models.ManyToManyField(blank=True, related_name='partners', to='partner.product')),
                ('testimonials', models.ManyToManyField(blank=True, related_name='partners', to='partner.testimonial')),
            ],
            options={
                'verbose_name': 'Partner Profile',
                'verbose_name_plural': 'Partner Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='partner_par_status_efd5ef_idx'), models.Index(fields=['referral_code'], name='partner_par_referra_ab57b9_idx'), models.Index(fields=['slug'], name='partner_par_slug_4f89e8_idx')],
            },
        ),
    ]
