# Generated by Django 5.2 on 2025-05-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='product_info_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
