# Generated by Django 5.2 on 2025-05-03 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partnerprofile_product_info_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faqs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='refund_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='booking_path',
            field=models.CharField(blank=True, default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='process_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='support_duration',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='svg_image',
            field=models.FileField(blank=True, null=True, upload_to='products/svg/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
