# Generated by Django 5.2 on 2025-05-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_product_faqs_product_refund_policy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='partner_pro_is_acti_d5fa2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='partner_pro_categor_f90cf3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='partner_pro_type_2f7041_idx',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='product_info_json',
        ),
        migrations.RemoveField(
            model_name='product',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refund_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AlterField(
            model_name='product',
            name='booking_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='exclusive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='process_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='support_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='svg_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Required for image testimonials', null=True, upload_to='testimonials/images/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Required for video testimonials', null=True, upload_to='testimonials/videos/'),
        ),
    ]
