# Generated by Django 5.2 on 2025-04-30 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=50)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('timeline', models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('1-3 months', '1-3 months'), ('3-6 months', '3-6 months'), ('6+ months', '6+ months')], max_length=20, null=True)),
                ('expected_implementation_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('prev_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('rejected', 'Rejected')], max_length=10, null=True)),
                ('potential_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='partner.partnerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='partner.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='ReferralTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_status_changes', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='referrals_management.referral')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'date_submitted'], name='referrals_m_status_13b65c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code'], name='referrals_m_referra_be2d90_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['user', 'status'], name='referrals_m_user_id_6fe75f_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['partner'], name='referrals_m_partner_c2b280_idx'),
        ),
    ]
