# Generated by Django 5.2 on 2025-05-22 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_remove_testimonial_is_approved_testimonial_status_and_more'),
        ('referrals_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='product_name',
            field=models.CharField(blank=True, help_text='Deprecated: Use product FK instead', max_length=255),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['product'], name='referrals_m_product_1589da_idx'),
        ),
    ]
