# Generated by Django 5.2 on 2025-04-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals_management', '0002_referral_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='product_name',
        ),
    ]
