# Generated by Django 5.2 on 2025-04-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals_management', '0003_remove_referral_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
